apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: DS_PROMETHEUS
    url: http://prometheus:9090
    isDefault: false
    version: 1
    editable: false
