global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: [ ]
scrape_configs:
  - job_name: weaviate
    static_configs:
      - targets:
          - weaviate:2112
  - job_name: mongodb
    static_configs:
      - targets: [ 'mongodb-exporter:9216' ]
  - job_name: minio
    metrics_path: /minio/prometheus/metrics
    scheme: http
    static_configs:
      - targets: [ 'minio:9000' ]
  - job_name: redis-exporter
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
  - job_name: fastapi
    metrics_path: /metrics
    static_configs:
      - targets: [ 'fastapi-backend:8068' ]